{{/*
Copyright (C) 2026 Garudex Labs.  All Rights Reserved.
Caracal, a product of Garudex Labs

PodDisruptionBudget templates for Caracal services.
*/}}

{{- range $name, $service := .Values.services }}
{{- if and $service.enabled $service.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "caracal.fullname" $ }}-{{ $name }}
  labels:
    {{- include "caracal.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  minAvailable: {{ $service.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "caracal.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $name }}
---
{{- end }}
{{- end }}
