{{/*
Copyright (C) 2026 Garudex Labs.  All Rights Reserved.
Caracal, a product of Garudex Labs

ServiceMonitor templates for Prometheus Operator installations.
*/}}

{{- if .Values.serviceMonitor.enabled }}
{{- range $name, $service := .Values.services }}
{{- if $service.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "caracal.fullname" $ }}-{{ $name }}
  labels:
    {{- include "caracal.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  selector:
    matchLabels:
      {{- include "caracal.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $name }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ $.Values.serviceMonitor.interval }}
---
{{- end }}
{{- end }}
{{- end }}
